export const CORE_TEMPLATES = [
  {
    name: 'Tint Red when HP is bellow 10%',
    hint: 'Tint token red when HP falls bellow 10%',
    order: 0,
    mappings: [
      {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {
          texture: {
            tint: '#ff0000',
          },
        },
        overlay: false,
        alwaysOn: false,
        disabled: false,
        overlayConfig: {
          label: 'hp<=10%',
        },
        targetActors: null,
        group: 'Default',
        label: 'hp<=10%',
        expression: 'hp<=10%',
      },
    ],
  },
  {
    name: 'Health State Text Overlay',
    hint: 'Displays text overlay based on percentage health.',
    order: 1,
    mappings: [
      {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {},
        overlay: true,
        alwaysOn: false,
        disabled: false,
        overlayConfig: {
          parent: '',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: false,
          linkScale: false,
          linkDimensionX: false,
          linkDimensionY: false,
          linkOpacity: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0,
          offsetY: 0.51,
          scaleX: 0.76,
          scaleY: 0.76,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 1,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: 'Critical',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#ff0000',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: null,
            },
          },
          label: 'hp>0 && hp<=25%',
        },
        targetActors: null,
        group: 'Health State Overlay',
        label: 'hp>0 && hp<=25%',
        expression: 'hp>0 && hp<=25%',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {},
        overlay: true,
        alwaysOn: false,
        disabled: false,
        overlayConfig: {
          parent: '',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: false,
          linkScale: false,
          linkDimensionX: false,
          linkDimensionY: false,
          linkOpacity: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0,
          offsetY: 0.51,
          scaleX: 0.76,
          scaleY: 0.76,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 1,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: 'Bloodied',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#ff5900',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: null,
            },
          },
          label: 'hp>25% && hp<=50%',
        },
        targetActors: null,
        group: 'Health State Overlay',
        label: 'hp>25% && hp<=50%',
        expression: 'hp>25% && hp<=50%',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {},
        overlay: true,
        alwaysOn: false,
        disabled: false,
        overlayConfig: {
          parent: '',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: false,
          linkScale: false,
          linkDimensionX: false,
          linkDimensionY: false,
          linkOpacity: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0,
          offsetY: 0.51,
          scaleX: 0.76,
          scaleY: 0.76,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 1,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: 'Wounded',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#ffbb00',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: null,
            },
          },
          label: 'hp>50% && hp<=75%',
        },
        targetActors: null,
        group: 'Health State Overlay',
        label: 'hp>50% && hp<=75%',
        expression: 'hp>50% && hp<=75%',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {},
        overlay: true,
        alwaysOn: false,
        disabled: false,
        overlayConfig: {
          parent: '',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: false,
          linkScale: false,
          linkDimensionX: false,
          linkDimensionY: false,
          linkOpacity: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0,
          offsetY: 0.51,
          scaleX: 0.76,
          scaleY: 0.76,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 1,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: 'Healthy',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#2bff00',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: null,
            },
          },
          label: 'hp>75%',
        },
        targetActors: null,
        group: 'Health State Overlay',
        label: 'hp>75%',
        expression: 'hp>75%',
      },
    ],
  },
  {
    name: 'Health State Text Overlay - Passed Check',
    hint: 'Same as `Health State Text Overlay` except also requiring the Token actor to have `Reveal Health` active effect applied to it.',
    order: 2,
    mappings: [
      {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {},
        overlay: true,
        alwaysOn: false,
        disabled: false,
        overlayConfig: {
          parent: '',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: false,
          linkScale: false,
          linkDimensionX: false,
          linkDimensionY: false,
          linkOpacity: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0,
          offsetY: 0.51,
          scaleX: 0.76,
          scaleY: 0.76,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 1,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: 'Critical',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#ff0000',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: null,
            },
          },
          label: 'Reveal Health && hp>0 && hp<=25%',
        },
        targetActors: null,
        group: 'Health State Overlay - Passed Check',
        label: 'Reveal Health && hp>0 && hp<=25%',
        expression: 'Reveal Health && hp>0 && hp<=25%',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {},
        overlay: true,
        alwaysOn: false,
        disabled: false,
        overlayConfig: {
          parent: '',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: false,
          linkScale: false,
          linkDimensionX: false,
          linkDimensionY: false,
          linkOpacity: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0,
          offsetY: 0.51,
          scaleX: 0.76,
          scaleY: 0.76,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 1,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: 'Bloodied',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#ff5900',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: null,
            },
          },
          label: 'Reveal Health && hp>25% && hp<=50%',
        },
        targetActors: null,
        group: 'Health State Overlay - Passed Check',
        label: 'Reveal Health && hp>25% && hp<=50%',
        expression: 'Reveal Health && hp>25% && hp<=50%',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {},
        overlay: true,
        alwaysOn: false,
        disabled: false,
        overlayConfig: {
          parent: '',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: false,
          linkScale: false,
          linkDimensionX: false,
          linkDimensionY: false,
          linkOpacity: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0,
          offsetY: 0.51,
          scaleX: 0.76,
          scaleY: 0.76,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 1,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: 'Wounded',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#ffbb00',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: null,
            },
          },
          label: 'Reveal Health && hp>50% && hp<=75%',
        },
        targetActors: null,
        group: 'Health State Overlay - Passed Check',
        label: 'Reveal Health && hp>50% && hp<=75%',
        expression: 'Reveal Health && hp>50% && hp<=75%',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {},
        overlay: true,
        alwaysOn: false,
        disabled: false,
        overlayConfig: {
          parent: '',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: false,
          linkScale: false,
          linkDimensionX: false,
          linkDimensionY: false,
          linkOpacity: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0,
          offsetY: 0.51,
          scaleX: 0.76,
          scaleY: 0.76,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 1,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: 'Healthy',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#2bff00',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: null,
            },
          },
          label: 'Reveal Health && hp>75%',
        },
        targetActors: null,
        group: 'Health State Overlay - Passed Check',
        label: 'Reveal Health && hp>75%',
        expression: 'Reveal Health && hp>75%',
      },
    ],
  },
  {
    name: 'Fancy Nameplate',
    hint: 'Displays a curved red nameplate underneath the token.',
    order: 3,
    mappings: [
      {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {},
        overlay: true,
        alwaysOn: true,
        disabled: false,
        overlayConfig: {
          parent: '',
          underlay: false,
          bottom: false,
          top: true,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: false,
          linkScale: false,
          linkDimensionX: false,
          linkDimensionY: false,
          linkOpacity: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0,
          offsetY: -0.51,
          scaleX: 0.68,
          scaleY: 0.68,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 0,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: '{{name}}',
            fontFamily: 'Modesto Condensed',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#ff0000',
            dropShadow: 'true',
            strokeThickness: 3,
            stroke: '#111111',
            curve: {
              radius: 450,
              invert: true,
            },
          },
          shapes: [
            {
              line: {
                width: 1,
                color: '#111111',
                alpha: 1,
              },
              fill: {
                color: '#111111',
                alpha: 1,
              },
            },
          ],
          label: 'Token Nameplate',
        },
        targetActors: null,
        group: 'Nameplate',
        label: 'Token Nameplate',
        expression: 'Token Nameplate',
      },
    ],
  },
  {
    name: 'Info Box #1',
    hint: 'Displays information about the token/actor when hovering over or controlling them. This box will adjust to canvas zoom.',
    order: 4,
    mappings: [
      {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {},
        overlay: true,
        alwaysOn: true,
        disabled: false,
        overlayConfig: {
          parent: '',
          underlay: false,
          bottom: false,
          top: true,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: false,
          linkScale: false,
          linkDimensionX: false,
          linkDimensionY: false,
          linkOpacity: false,
          linkStageScale: true,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: -0.55,
          offsetY: 0,
          scaleX: 0.73,
          scaleY: 0.73,
          angle: 0,
          anchor: {
            x: 0,
            y: 0.5,
          },
          filter: 'DropShadowFilter',
          filterOptions: {
            rotation: 45,
            distance: 16.9,
            color: '#000000',
            alpha: 0.52,
            shadowOnly: false,
            blur: 2,
            quality: 3,
          },
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: true,
          limitOnControl: true,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: '',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: false,
            },
          },
          shapes: [
            {
              shape: {
                type: 'rectangle',
                x: 0,
                y: 0,
                width: 450,
                height: 200,
                radius: 0,
              },
              line: {
                width: 2,
                color: '#ffffff',
                alpha: 1,
              },
              fill: {
                color: '#508fe2',
                alpha: 0.55,
              },
            },
          ],
          label: 'Text Box Background',
        },
        targetActors: null,
        group: 'Info Box',
        label: 'Text Box Background',
        expression: 'Text Box Background',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {},
        overlay: true,
        alwaysOn: true,
        disabled: false,
        overlayConfig: {
          parent: 'Text Box Background',
          underlay: false,
          bottom: false,
          top: true,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: false,
          linkScale: false,
          linkOpacity: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: -0.25,
          offsetY: 0.46,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          anchor: {
            x: 0,
            y: 0,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          text: {
            text: 'AC: {{actor.system.attributes.ac.value}}',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: null,
            },
          },
          label: 'Actor AC',
        },
        targetActors: null,
        group: 'Info Box',
        label: 'Actor AC',
        expression: 'Actor AC',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {},
        overlay: true,
        alwaysOn: false,
        disabled: false,
        overlayConfig: {
          parent: 'Text Box Background',
          underlay: false,
          bottom: false,
          top: true,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: false,
          linkScale: false,
          linkOpacity: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0.47,
          offsetY: -0.02,
          scaleX: 0.5,
          scaleY: 0.5,
          angle: 0,
          anchor: {
            x: 0,
            y: 0,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          text: {
            text: 'Legendary: Action {{actor.system.resources.legact.value}}/{{actor.system.resources.legact.max}} Resistance {{actor.system.resources.legres.value}}/{{actor.system.resources.legres.max}}',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: null,
            },
          },
          label: 'actor.system.resources.legact.max>0',
        },
        targetActors: null,
        group: 'Info Box',
        label: 'actor.system.resources.legact.max>0',
        expression: 'actor.system.resources.legact.max>0',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {},
        overlay: true,
        alwaysOn: false,
        disabled: false,
        overlayConfig: {
          parent: 'Text Box Background',
          underlay: false,
          bottom: false,
          top: true,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: false,
          linkScale: false,
          linkOpacity: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0.47,
          offsetY: 0.23,
          scaleX: 0.82,
          scaleY: 0.82,
          angle: 0,
          anchor: {
            x: 0,
            y: 0,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          text: {
            text: 'HP: {{actor.system.attributes.hp.value}}/{{actor.system.attributes.hp.max}}',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#ff0000',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#6b6b6b',
            curve: {
              radius: 0,
              invert: null,
            },
          },
          label: 'hp<=40%',
        },
        targetActors: null,
        group: 'Info Box',
        label: 'hp<=40%',
        expression: 'hp<=40%',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {},
        overlay: true,
        alwaysOn: false,
        disabled: false,
        overlayConfig: {
          parent: 'Text Box Background',
          underlay: false,
          bottom: false,
          top: true,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: false,
          linkScale: false,
          linkOpacity: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0.47,
          offsetY: 0.23,
          scaleX: 0.82,
          scaleY: 0.82,
          angle: 0,
          anchor: {
            x: 0,
            y: 0,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          text: {
            text: 'HP: {{actor.system.attributes.hp.value}}/{{actor.system.attributes.hp.max}}',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#6b6b6b',
            curve: {
              radius: 0,
              invert: null,
            },
          },
          label: 'hp>40%',
        },
        targetActors: null,
        group: 'Info Box',
        label: 'hp>40%',
        expression: 'hp>40%',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {},
        overlay: true,
        alwaysOn: true,
        disabled: false,
        overlayConfig: {
          parent: 'Text Box Background',
          underlay: false,
          bottom: false,
          top: true,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: false,
          linkScale: false,
          linkOpacity: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0,
          offsetY: -0.38,
          scaleX: 0.57,
          scaleY: 0.57,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 0.5,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          text: {
            text: 'STR {{actor.system.abilities.str.mod}}  DEX {{actor.system.abilities.dex.mod}}  CON {{actor.system.abilities.con.mod}}  INT {{actor.system.abilities.int.mod}}  WIS {{actor.system.abilities.wis.mod}}  CHA {{actor.system.abilities.cha.mod}}',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: null,
            },
          },
          label: 'Mods',
        },
        targetActors: null,
        group: 'Info Box',
        label: 'Mods',
        expression: 'Mods',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {},
        overlay: true,
        alwaysOn: true,
        disabled: false,
        overlayConfig: {
          parent: 'Text Box Background',
          underlay: false,
          bottom: false,
          top: true,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: false,
          linkScale: false,
          linkOpacity: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: -0.36,
          offsetY: -0.16,
          scaleX: 0.33,
          scaleY: 0.33,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 0.5,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          text: {
            text: 'Fly {{actor.system.attributes.movement.fly}}, Swim {{actor.system.attributes.movement.swim}}',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: null,
            },
          },
          label: 'Movement Fly',
        },
        targetActors: null,
        group: 'Info Box',
        label: 'Movement Fly',
        expression: 'Movement Fly',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {},
        overlay: true,
        alwaysOn: true,
        disabled: false,
        overlayConfig: {
          parent: 'Text Box Background',
          underlay: false,
          bottom: false,
          top: true,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: false,
          linkScale: false,
          linkOpacity: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: -0.25,
          offsetY: 0.2,
          scaleX: 0.61,
          scaleY: 0.61,
          angle: 0,
          anchor: {
            x: 0,
            y: 0,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          text: {
            text: 'Movement',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: null,
            },
          },
          label: 'Movement Label',
        },
        targetActors: null,
        group: 'Info Box',
        label: 'Movement Label',
        expression: 'Movement Label',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {},
        overlay: true,
        alwaysOn: true,
        disabled: false,
        overlayConfig: {
          parent: 'Text Box Background',
          underlay: false,
          bottom: false,
          top: true,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: false,
          linkScale: false,
          linkOpacity: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: -0.36,
          offsetY: -0.03,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 0.5,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          text: {
            text: '{{actor.system.attributes.movement.walk}}ft',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: null,
            },
          },
          label: 'Movement Walk',
        },
        targetActors: null,
        group: 'Info Box',
        label: 'Movement Walk',
        expression: 'Movement Walk',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {},
        overlay: true,
        alwaysOn: true,
        disabled: false,
        overlayConfig: {
          parent: 'Text Box Background',
          underlay: false,
          bottom: false,
          top: true,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: false,
          linkScale: false,
          linkOpacity: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0.47,
          offsetY: 0.35,
          scaleX: 0.77,
          scaleY: 0.77,
          angle: 0,
          anchor: {
            x: 0,
            y: 0.5,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          text: {
            text: 'Name: {{name}}',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: null,
            },
          },
          label: 'Token Name',
        },
        targetActors: null,
        group: 'Info Box',
        label: 'Token Name',
        expression: 'Token Name',
      },
    ],
  },
  {
    name: 'Info Box #2',
    hint: 'Displays information about the token/actor when hovering over or controlling them. This box will adjust to canvas zoom.',
    order: 5,
    mappings: [
      {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {},
        overlay: true,
        alwaysOn: true,
        disabled: false,
        overlayConfig: {
          parent: '',
          underlay: false,
          bottom: false,
          top: true,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: false,
          linkScale: false,
          linkDimensionX: false,
          linkDimensionY: false,
          linkOpacity: false,
          linkStageScale: true,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: -0.55,
          offsetY: 0,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          anchor: {
            x: 0,
            y: 0.5,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: true,
          limitOnControl: true,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: '',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: false,
            },
          },
          shapes: [
            {
              shape: {
                type: 'rectangle',
                x: 0,
                y: 0,
                width: 200,
                height: 300,
                radius: 0,
              },
              line: {
                width: 2,
                color: '#ffffff',
                alpha: 1,
              },
              fill: {
                color: '#2e5a94',
                alpha: 0.9,
              },
            },
          ],
          label: 'Info Box #2 Background',
        },
        targetActors: null,
        group: 'Info Box #2',
        label: 'Info Box #2 Background',
        expression: 'Info Box #2 Background',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 51,
        config: {},
        overlay: true,
        alwaysOn: true,
        disabled: false,
        overlayConfig: {
          parent: 'Info Box #2 Background',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: true,
          linkScale: true,
          linkDimensionX: false,
          linkDimensionY: false,
          linkOpacity: false,
          linkStageScale: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0.45,
          offsetY: 0.42,
          scaleX: 0.84,
          scaleY: 0.84,
          angle: 0,
          anchor: {
            x: 0,
            y: 0.5,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: 'HP: {{actor.system.attributes.hp.value}}/{{actor.system.attributes.hp.max}}',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: false,
            },
          },
          label: 'Info Box #2 - HP',
        },
        targetActors: null,
        group: 'Info Box #2',
        label: 'Info Box #2 - HP',
        expression: 'Info Box #2 - HP',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 52,
        config: {},
        overlay: true,
        alwaysOn: true,
        disabled: false,
        overlayConfig: {
          parent: 'Info Box #2 Background',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: true,
          linkScale: true,
          linkDimensionX: false,
          linkDimensionY: false,
          linkOpacity: false,
          linkStageScale: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0.45,
          offsetY: 0.31,
          scaleX: 0.84,
          scaleY: 0.84,
          angle: 0,
          anchor: {
            x: 0,
            y: 0.5,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: 'AC: {{actor.system.attributes.ac.value}}',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: false,
            },
          },
          label: 'Info Box #2 - AC',
        },
        targetActors: null,
        group: 'Info Box #2',
        label: 'Info Box #2 - AC',
        expression: 'Info Box #2 - AC',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 53,
        config: {},
        overlay: true,
        alwaysOn: true,
        disabled: false,
        overlayConfig: {
          parent: 'Info Box #2 Background',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: true,
          linkScale: true,
          linkDimensionX: false,
          linkDimensionY: false,
          linkOpacity: false,
          linkStageScale: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0.45,
          offsetY: 0.2,
          scaleX: 0.84,
          scaleY: 0.84,
          angle: 0,
          anchor: {
            x: 0,
            y: 0.5,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: 'Speed: {{actor.system.attributes.movement.walk}}ft',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: false,
            },
          },
          label: 'Info Box #2 - Speed',
        },
        targetActors: null,
        group: 'Info Box #2',
        label: 'Info Box #2 - Speed',
        expression: 'Info Box #2 - Speed',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 54,
        config: {},
        overlay: true,
        alwaysOn: true,
        disabled: false,
        overlayConfig: {
          parent: 'Info Box #2 Background',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: true,
          linkScale: true,
          linkDimensionX: false,
          linkDimensionY: false,
          linkOpacity: false,
          linkStageScale: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0,
          offsetY: 0.15,
          scaleX: 0.84,
          scaleY: 0.84,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 0,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: 'Perception',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: false,
            },
          },
          label: 'Info Box #2 - Perception',
        },
        targetActors: null,
        group: 'Info Box #2',
        label: 'Info Box #2 - Perception',
        expression: 'Info Box #2 - Perception',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 55,
        config: {},
        overlay: true,
        alwaysOn: true,
        disabled: false,
        overlayConfig: {
          parent: 'Info Box #2 Background',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: true,
          linkScale: true,
          linkDimensionX: false,
          linkDimensionY: false,
          linkOpacity: false,
          linkStageScale: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0.47,
          offsetY: 0,
          scaleX: 0.51,
          scaleY: 0.51,
          angle: 0,
          anchor: {
            x: 0,
            y: 0.5,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: 'Passive: {{actor.system.skills.prc.passive}}',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: false,
            },
          },
          label: 'Info Box #2 - Prc. Passive',
        },
        targetActors: null,
        group: 'Info Box #2',
        label: 'Info Box #2 - Prc. Passive',
        expression: 'Info Box #2 - Prc. Passive',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 56,
        config: {},
        overlay: true,
        alwaysOn: true,
        disabled: false,
        overlayConfig: {
          parent: 'Info Box #2 Background',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: true,
          linkScale: true,
          linkDimensionX: false,
          linkDimensionY: false,
          linkOpacity: false,
          linkStageScale: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: -0.48,
          offsetY: 0,
          scaleX: 0.51,
          scaleY: 0.51,
          angle: 0,
          anchor: {
            x: 1,
            y: 0.5,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: 'Active: {{actor.system.skills.prc.total}}',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: false,
            },
          },
          label: 'Info Box #2 - Prc. Active',
        },
        targetActors: null,
        group: 'Info Box #2',
        label: 'Info Box #2 - Prc. Active',
        expression: 'Info Box #2 - Prc. Active',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 57,
        config: {},
        overlay: true,
        alwaysOn: true,
        disabled: false,
        overlayConfig: {
          parent: 'Info Box #2 Background',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: true,
          linkScale: true,
          linkDimensionX: false,
          linkDimensionY: false,
          linkOpacity: false,
          linkStageScale: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: -0.31,
          offsetY: -0.3,
          scaleX: 0.51,
          scaleY: 0.51,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 0,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: 'CHA\\n{{actor.system.abilities.cha.mod}} {{actor.system.abilities.cha.save}}',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: false,
            },
          },
          label: 'Info Box #2 - CHA',
        },
        targetActors: null,
        group: 'Info Box #2',
        label: 'Info Box #2 - CHA',
        expression: 'Info Box #2 - CHA',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 57,
        config: {},
        overlay: true,
        alwaysOn: true,
        disabled: false,
        overlayConfig: {
          parent: 'Info Box #2 Background',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: true,
          linkScale: true,
          linkDimensionX: false,
          linkDimensionY: false,
          linkOpacity: false,
          linkStageScale: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: -0.31,
          offsetY: -0.11,
          scaleX: 0.51,
          scaleY: 0.51,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 0,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: 'CON\\n{{actor.system.abilities.con.mod}} {{actor.system.abilities.con.save}}',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: false,
            },
          },
          label: 'Info Box #2 - CON',
        },
        targetActors: null,
        group: 'Info Box #2',
        label: 'Info Box #2 - CON',
        expression: 'Info Box #2 - CON',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 57,
        config: {},
        overlay: true,
        alwaysOn: true,
        disabled: false,
        overlayConfig: {
          parent: 'Info Box #2 Background',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: true,
          linkScale: true,
          linkDimensionX: false,
          linkDimensionY: false,
          linkOpacity: false,
          linkStageScale: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0,
          offsetY: -0.11,
          scaleX: 0.51,
          scaleY: 0.51,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 0,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: 'DEX\\n{{actor.system.abilities.dex.mod}} {{actor.system.abilities.dex.save}}',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: false,
            },
          },
          label: 'Info Box #2 - DEX',
        },
        targetActors: null,
        group: 'Info Box #2',
        label: 'Info Box #2 - DEX',
        expression: 'Info Box #2 - DEX',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 57,
        config: {},
        overlay: true,
        alwaysOn: true,
        disabled: false,
        overlayConfig: {
          parent: 'Info Box #2 Background',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: true,
          linkScale: true,
          linkDimensionX: false,
          linkDimensionY: false,
          linkOpacity: false,
          linkStageScale: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0.32,
          offsetY: -0.3,
          scaleX: 0.51,
          scaleY: 0.51,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 0,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: 'INT\\n{{actor.system.abilities.int.mod}} {{actor.system.abilities.int.save}}',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: false,
            },
          },
          label: 'Info Box #2 - INT',
        },
        targetActors: null,
        group: 'Info Box #2',
        label: 'Info Box #2 - INT',
        expression: 'Info Box #2 - INT',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 57,
        config: {},
        overlay: true,
        alwaysOn: true,
        disabled: false,
        overlayConfig: {
          parent: 'Info Box #2 Background',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: true,
          linkScale: true,
          linkDimensionX: false,
          linkDimensionY: false,
          linkOpacity: false,
          linkStageScale: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0.32,
          offsetY: -0.11,
          scaleX: 0.51,
          scaleY: 0.51,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 0,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: 'STR\\n{{actor.system.abilities.str.mod}} {{actor.system.abilities.str.save}}',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: false,
            },
          },
          label: 'Info Box #2 - STR',
        },
        targetActors: null,
        group: 'Info Box #2',
        label: 'Info Box #2 - STR',
        expression: 'Info Box #2 - STR',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 57,
        config: {},
        overlay: true,
        alwaysOn: true,
        disabled: false,
        overlayConfig: {
          parent: 'Info Box #2 Background',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: true,
          linkScale: true,
          linkDimensionX: false,
          linkDimensionY: false,
          linkOpacity: false,
          linkStageScale: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0,
          offsetY: -0.3,
          scaleX: 0.51,
          scaleY: 0.51,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 0,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: 'WIS\\n{{actor.system.abilities.wis.mod}} {{actor.system.abilities.wis.save}}',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: false,
            },
          },
          label: 'Info Box #2 - WIS',
        },
        targetActors: null,
        group: 'Info Box #2',
        label: 'Info Box #2 - WIS',
        expression: 'Info Box #2 - WIS',
      },
    ],
  },
  {
    name: 'Info Box #3',
    hint: 'Displays information about the token/actor when hovering over or controlling them. This box will adjust to canvas zoom.',
    order: 6,
    mappings: [
      {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {},
        overlay: true,
        alwaysOn: true,
        disabled: false,
        overlayConfig: {
          parent: '',
          underlay: false,
          bottom: false,
          top: true,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: false,
          linkScale: false,
          linkDimensionX: false,
          linkDimensionY: false,
          linkOpacity: false,
          linkStageScale: true,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: -0.55,
          offsetY: 0,
          scaleX: 1,
          scaleY: 1,
          angle: 0,
          anchor: {
            x: 0,
            y: 0.5,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: true,
          limitOnControl: true,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: '',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: false,
            },
          },
          shapes: [
            {
              shape: {
                type: 'rectangle',
                x: 0,
                y: 0,
                width: 240,
                height: 300,
                radius: 0,
              },
              line: {
                width: 2,
                color: '#ffffff',
                alpha: 1,
              },
              fill: {
                color: '#2e5a94',
                alpha: 0.9,
              },
            },
          ],
          label: 'Info Box #3 Background',
        },
        targetActors: null,
        group: 'Info Box #3',
        label: 'Info Box #3 Background',
        expression: 'Info Box #3 Background',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 51,
        config: {},
        overlay: true,
        alwaysOn: true,
        disabled: false,
        overlayConfig: {
          parent: 'Info Box #3 Background',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: true,
          linkScale: true,
          linkDimensionX: false,
          linkDimensionY: false,
          linkOpacity: false,
          linkStageScale: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0.44,
          offsetY: 0.42,
          scaleX: 0.84,
          scaleY: 0.84,
          angle: 0,
          anchor: {
            x: 0,
            y: 0.5,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: ' {{actor.system.attributes.hp.value}}/{{actor.system.attributes.hp.max}}',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: false,
            },
          },
          label: 'Info Box #3 - HP',
        },
        targetActors: null,
        group: 'Info Box #3',
        label: 'Info Box #3 - HP',
        expression: 'Info Box #3 - HP',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 52,
        config: {},
        overlay: true,
        alwaysOn: true,
        disabled: false,
        overlayConfig: {
          parent: 'Info Box #3 Background',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: true,
          linkScale: true,
          linkDimensionX: false,
          linkDimensionY: false,
          linkOpacity: false,
          linkStageScale: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0.43,
          offsetY: 0.28,
          scaleX: 0.84,
          scaleY: 0.84,
          angle: 0,
          anchor: {
            x: 0,
            y: 0.5,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: ' {{actor.system.attributes.ac.value}}',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: false,
            },
          },
          label: 'Info Box #3 - AC',
        },
        targetActors: null,
        group: 'Info Box #3',
        label: 'Info Box #3 - AC',
        expression: 'Info Box #3 - AC',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 55,
        config: {},
        overlay: true,
        alwaysOn: true,
        disabled: false,
        overlayConfig: {
          parent: 'Info Box #3 Background',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: true,
          linkScale: true,
          linkDimensionX: false,
          linkDimensionY: false,
          linkOpacity: false,
          linkStageScale: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0.45,
          offsetY: -0.02,
          scaleX: 0.83,
          scaleY: 0.83,
          angle: 0,
          anchor: {
            x: 0,
            y: 0.5,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: ' {{actor.system.skills.prc.passive}}',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: false,
            },
          },
          label: 'Info Box #3 - Prc. Passive',
        },
        targetActors: null,
        group: 'Info Box #3',
        label: 'Info Box #3 - Prc. Passive',
        expression: 'Info Box #3 - Prc. Passive',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 56,
        config: {},
        overlay: true,
        alwaysOn: true,
        disabled: false,
        overlayConfig: {
          parent: 'Info Box #3 Background',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: true,
          linkScale: true,
          linkDimensionX: false,
          linkDimensionY: false,
          linkOpacity: false,
          linkStageScale: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: -0.03,
          offsetY: -0.02,
          scaleX: 0.83,
          scaleY: 0.83,
          angle: 0,
          anchor: {
            x: 0,
            y: 0.5,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: ' {{actor.system.skills.prc.total}}',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: false,
            },
          },
          label: 'Info Box #3 - Prc. Active',
        },
        targetActors: null,
        group: 'Info Box #3',
        label: 'Info Box #3 - Prc. Active',
        expression: 'Info Box #3 - Prc. Active',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 57,
        config: {},
        overlay: true,
        alwaysOn: true,
        disabled: false,
        overlayConfig: {
          parent: 'Info Box #3 Background',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: true,
          linkScale: true,
          linkDimensionX: false,
          linkDimensionY: false,
          linkOpacity: false,
          linkStageScale: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: -0.31,
          offsetY: -0.3,
          scaleX: 0.51,
          scaleY: 0.51,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 0,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: 'CHA\\n{{actor.system.abilities.cha.mod}}  {{actor.system.abilities.cha.save}}',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: false,
            },
          },
          label: 'Info Box #3 - CHA',
        },
        targetActors: null,
        group: 'Info Box #3',
        label: 'Info Box #3 - CHA',
        expression: 'Info Box #3 - CHA',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 57,
        config: {},
        overlay: true,
        alwaysOn: true,
        disabled: false,
        overlayConfig: {
          parent: 'Info Box #3 Background',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: true,
          linkScale: true,
          linkDimensionX: false,
          linkDimensionY: false,
          linkOpacity: false,
          linkStageScale: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: -0.31,
          offsetY: -0.11,
          scaleX: 0.51,
          scaleY: 0.51,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 0,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: 'CON\\n{{actor.system.abilities.con.mod}}  {{actor.system.abilities.con.save}}',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: false,
            },
          },
          label: 'Info Box #3 - CON',
        },
        targetActors: null,
        group: 'Info Box #3',
        label: 'Info Box #3 - CON',
        expression: 'Info Box #3 - CON',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 57,
        config: {},
        overlay: true,
        alwaysOn: true,
        disabled: false,
        overlayConfig: {
          parent: 'Info Box #3 Background',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: true,
          linkScale: true,
          linkDimensionX: false,
          linkDimensionY: false,
          linkOpacity: false,
          linkStageScale: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0,
          offsetY: -0.11,
          scaleX: 0.51,
          scaleY: 0.51,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 0,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: 'DEX\\n{{actor.system.abilities.dex.mod}}  {{actor.system.abilities.dex.save}}',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: false,
            },
          },
          label: 'Info Box #3 - DEX',
        },
        targetActors: null,
        group: 'Info Box #3',
        label: 'Info Box #3 - DEX',
        expression: 'Info Box #3 - DEX',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 57,
        config: {},
        overlay: true,
        alwaysOn: true,
        disabled: false,
        overlayConfig: {
          parent: 'Info Box #3 Background',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: true,
          linkScale: true,
          linkDimensionX: false,
          linkDimensionY: false,
          linkOpacity: false,
          linkStageScale: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0.32,
          offsetY: -0.3,
          scaleX: 0.51,
          scaleY: 0.51,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 0,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: 'INT\\n{{actor.system.abilities.int.mod}}  {{actor.system.abilities.int.save}}',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: false,
            },
          },
          label: 'Info Box #3 - INT',
        },
        targetActors: null,
        group: 'Info Box #3',
        label: 'Info Box #3 - INT',
        expression: 'Info Box #3 - INT',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 57,
        config: {},
        overlay: true,
        alwaysOn: true,
        disabled: false,
        overlayConfig: {
          parent: 'Info Box #3 Background',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: true,
          linkScale: true,
          linkDimensionX: false,
          linkDimensionY: false,
          linkOpacity: false,
          linkStageScale: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0.32,
          offsetY: -0.11,
          scaleX: 0.51,
          scaleY: 0.51,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 0,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: 'STR\\n{{actor.system.abilities.str.mod}}  {{actor.system.abilities.str.save}}',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: false,
            },
          },
          label: 'Info Box #3 - STR',
        },
        targetActors: null,
        group: 'Info Box #3',
        label: 'Info Box #3 - STR',
        expression: 'Info Box #3 - STR',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 57,
        config: {},
        overlay: true,
        alwaysOn: true,
        disabled: false,
        overlayConfig: {
          parent: 'Info Box #3 Background',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: true,
          linkScale: true,
          linkDimensionX: false,
          linkDimensionY: false,
          linkOpacity: false,
          linkStageScale: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0,
          offsetY: -0.3,
          scaleX: 0.51,
          scaleY: 0.51,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 0,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: 'WIS\\n{{actor.system.abilities.wis.mod}}  {{actor.system.abilities.wis.save}}',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: false,
            },
          },
          label: 'Info Box #3 - WIS',
        },
        targetActors: null,
        group: 'Info Box #3',
        label: 'Info Box #3 - WIS',
        expression: 'Info Box #3 - WIS',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 53,
        config: {},
        overlay: true,
        alwaysOn: true,
        disabled: false,
        overlayConfig: {
          parent: 'Info Box #3 Background',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: true,
          linkScale: true,
          linkDimensionX: false,
          linkDimensionY: false,
          linkOpacity: false,
          linkStageScale: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0.45,
          offsetY: 0.13,
          scaleX: 0.84,
          scaleY: 0.84,
          angle: 0,
          anchor: {
            x: 0,
            y: 0.5,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: ' {{actor.system.attributes.movement.walk}}ft',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: false,
            },
          },
          label: 'Info Box #3 - Walk Speed',
        },
        targetActors: null,
        group: 'Info Box #3',
        label: 'Info Box #3 - Walk Speed',
        expression: 'Info Box #3 - Walk Speed',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 53,
        config: {},
        overlay: true,
        alwaysOn: true,
        disabled: false,
        overlayConfig: {
          parent: 'Info Box #3 Background',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: true,
          linkScale: true,
          linkDimensionX: false,
          linkDimensionY: false,
          linkOpacity: false,
          linkStageScale: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: -0.04,
          offsetY: 0.13,
          scaleX: 0.84,
          scaleY: 0.84,
          angle: 0,
          anchor: {
            x: 0,
            y: 0.5,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: ' {{actor.system.attributes.movement.fly}}ft',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: false,
            },
          },
          label: 'Info Box #3 - Fly Speed',
        },
        targetActors: null,
        group: 'Info Box #3',
        label: 'Info Box #3 - Fly Speed',
        expression: 'Info Box #3 - Fly Speed',
      },
    ],
  },
  {
    name: 'Facing Direction',
    hint: 'Displays an arrow in the top-left corner of the token showing the direction it is facing.',
    order: 7,
    mappings: [
      {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {},
        overlay: true,
        alwaysOn: true,
        disabled: false,
        overlayConfig: {
          parent: '',
          underlay: false,
          bottom: false,
          top: true,
          inheritTint: false,
          linkRotation: true,
          animation: {
            relative: true,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: false,
          linkScale: false,
          linkDimensionX: true,
          linkDimensionY: true,
          linkOpacity: false,
          linkStageScale: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0.5,
          offsetY: 0.5,
          scaleX: 0.51,
          scaleY: 0.51,
          angle: 90,
          anchor: {
            x: 0.5,
            y: 0.5,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: '➢',
            fontFamily: 'Signika',
            fontSize: 63,
            letterSpacing: 0,
            fill: '#ff0000',
            dropShadow: null,
            strokeThickness: 3,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: false,
            },
          },
          label: 'Facing Direction',
        },
        targetActors: null,
        group: 'Facing Direction',
        label: 'Facing Direction',
        expression: 'Facing Direction',
      },
    ],
  },
  {
    name: 'Combat Markers',
    hint: "Displays rotating markers for tokens in combat. Green if it is that tokens turn, and orange if it's turn is next.",
    mappings: [
      {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {},
        overlay: true,
        alwaysOn: false,
        disabled: false,
        overlayConfig: {
          parent: '',
          underlay: true,
          bottom: true,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: true,
            duration: 30000,
            clockwise: true,
          },
          linkMirror: false,
          linkScale: false,
          linkDimensionX: true,
          linkDimensionY: true,
          linkOpacity: false,
          linkStageScale: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 0.55,
          tint: '',
          offsetX: 0,
          offsetY: 0,
          scaleX: 1.37,
          scaleY: 1.37,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 0.5,
          },
          filter: 'BloomFilter',
          filterOptions: {
            blur: 12,
            quality: 4,
          },
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: '',
            fontFamily: 'Signika',
            fontSize: 100,
            letterSpacing: 0,
            fill: '#8bfd3f',
            dropShadow: null,
            strokeThickness: 0,
            stroke: '#ffffff',
            curve: {
              radius: 0,
              invert: false,
            },
          },
          label: 'combat-turn',
        },
        targetActors: null,
        group: 'Combat Markers',
        label: 'combat-turn',
        expression: 'combat-turn',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {},
        overlay: true,
        alwaysOn: false,
        disabled: false,
        overlayConfig: {
          parent: '',
          underlay: true,
          bottom: true,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: true,
            duration: 30000,
            clockwise: true,
          },
          linkMirror: false,
          linkScale: false,
          linkDimensionX: true,
          linkDimensionY: true,
          linkOpacity: false,
          linkStageScale: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 0.5,
          tint: '',
          offsetX: 0,
          offsetY: 0,
          scaleX: 1.37,
          scaleY: 1.37,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 0.5,
          },
          filter: 'BloomFilter',
          filterOptions: {
            blur: 12,
            quality: 4,
          },
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: '',
            fontFamily: 'Signika',
            fontSize: 100,
            letterSpacing: 0,
            fill: '#ff9500',
            dropShadow: null,
            strokeThickness: 0,
            stroke: '#ffffff',
            curve: {
              radius: 0,
              invert: false,
            },
          },
          label: 'combat-turn-next',
        },
        targetActors: null,
        group: 'Combat Markers',
        label: 'combat-turn-next',
        expression: 'combat-turn-next',
      },
    ],
  },
  {
    name: 'Disposition Markers',
    hint: 'Displays circles underneath tokens coloured based on their disposition.',
    mappings: [
      {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {},
        overlay: true,
        alwaysOn: false,
        disabled: false,
        overlayConfig: {
          parent: '',
          underlay: true,
          bottom: true,
          top: false,
          inheritTint: false,
          linkRotation: true,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: true,
          linkScale: false,
          linkDimensionX: true,
          linkDimensionY: true,
          linkOpacity: false,
          linkStageScale: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0,
          offsetY: 0,
          scaleX: 0.24,
          scaleY: 0.24,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 0.5,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: '',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: false,
            },
          },
          shapes: [
            {
              shape: {
                type: 'ellipse',
                x: 0,
                y: 0,
                width: 250,
                height: 250,
              },
              line: {
                width: 0,
                color: '#000000',
                alpha: 1,
              },
              fill: {
                color: '#ffffff',
                alpha: 0.75,
              },
            },
            {
              shape: {
                type: 'ellipse',
                x: 0,
                y: 0,
                width: 220,
                height: 220,
              },
              line: {
                width: 0,
                color: '#000000',
                alpha: 1,
              },
              fill: {
                color: '#b8b8b8',
                alpha: 0.7,
              },
            },
          ],
          label: 'disposition=0',
        },
        targetActors: null,
        group: 'Disposition Markers',
        label: 'disposition=0',
        expression: 'disposition=0',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {},
        overlay: true,
        alwaysOn: false,
        disabled: false,
        overlayConfig: {
          parent: '',
          underlay: true,
          bottom: true,
          top: false,
          inheritTint: false,
          linkRotation: true,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: true,
          linkScale: false,
          linkDimensionX: true,
          linkDimensionY: true,
          linkOpacity: false,
          linkStageScale: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '#89fb79',
          offsetX: 0,
          offsetY: 0,
          scaleX: 0.24,
          scaleY: 0.24,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 0.5,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: '',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: false,
            },
          },
          shapes: [
            {
              shape: {
                type: 'ellipse',
                x: 0,
                y: 0,
                width: 250,
                height: 250,
              },
              line: {
                width: 0,
                color: '#000000',
                alpha: 1,
              },
              fill: {
                color: '#ffffff',
                alpha: 0.75,
              },
            },
            {
              shape: {
                type: 'ellipse',
                x: 0,
                y: 0,
                width: 220,
                height: 220,
              },
              line: {
                width: 0,
                color: '#000000',
                alpha: 1,
              },
              fill: {
                color: '#b8b8b8',
                alpha: 0.7,
              },
            },
          ],
          label: 'disposition=1',
        },
        targetActors: null,
        group: 'Disposition Markers',
        label: 'disposition=1',
        expression: 'disposition=1',
      },
      {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {},
        overlay: true,
        alwaysOn: false,
        disabled: false,
        overlayConfig: {
          parent: '',
          underlay: true,
          bottom: true,
          top: false,
          inheritTint: false,
          linkRotation: true,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: true,
          linkScale: false,
          linkDimensionX: true,
          linkDimensionY: true,
          linkOpacity: false,
          linkStageScale: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '#ff3838',
          offsetX: 0,
          offsetY: 0,
          scaleX: 0.24,
          scaleY: 0.24,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 0.5,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: '',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#FFFFFF',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: false,
            },
          },
          shapes: [
            {
              shape: {
                type: 'ellipse',
                x: 0,
                y: 0,
                width: 250,
                height: 250,
              },
              line: {
                width: 0,
                color: '#000000',
                alpha: 1,
              },
              fill: {
                color: '#ffffff',
                alpha: 0.75,
              },
            },
            {
              shape: {
                type: 'ellipse',
                x: 0,
                y: 0,
                width: 220,
                height: 220,
              },
              line: {
                width: 0,
                color: '#000000',
                alpha: 1,
              },
              fill: {
                color: '#b8b8b8',
                alpha: 0.7,
              },
            },
          ],
          label: 'disposition<0',
        },
        targetActors: null,
        group: 'Disposition Markers',
        label: 'disposition<0',
        expression: 'disposition<0',
      },
    ],
  },
];
