export const DEFAULT_ACTIVE_EFFECT_CONFIG = {
  effectName: '',
  imgName: '',
  imgSrc: '',
  priority: 50,
  config: null,
  overlay: false,
  alwaysOn: false,
  disabled: false,
  overlayConfig: null,
  targetActors: null,
  group: 'Default',
};

export const DEFAULT_OVERLAY_CONFIG = {
  img: '',
  alpha: 1,
  scaleX: 1,
  scaleY: 1,
  offsetX: 0,
  offsetY: 0,
  angle: 0,
  filter: 'NONE',
  filterOptions: {},
  inheritTint: false,
  top: false,
  bottom: false,
  underlay: false,
  linkRotation: true,
  linkMirror: true,
  linkOpacity: false,
  linkScale: true,
  linkDimensions: false,
  linkStageScale: false,
  mirror: false,
  tint: null,
  loop: true,
  playOnce: false,
  animation: {
    rotate: false,
    duration: 5000,
    clockwise: true,
    relative: false,
  },
  limitedUsers: [],
  alwaysVisible: false,
  text: {
    text: '',
    fontSize: CONFIG.canvasTextStyle.fontSize,
    fontFamily: CONFIG.canvasTextStyle.fontFamily,
    fill: CONFIG.canvasTextStyle.fill,
    dropShadow: CONFIG.canvasTextStyle.dropShadow,
    strokeThickness: CONFIG.canvasTextStyle.strokeThickness,
    stroke: CONFIG.canvasTextStyle.stroke,
    curve: { radius: 0, invert: false },
    letterSpacing: CONFIG.canvasTextStyle.letterSpacing,
  },
  parent: '',
  anchor: { x: 0.5, y: 0.5 },
  shapes: [],
};

export const OVERLAY_SHAPES = {
  Rectangle: {
    type: 'rectangle',
    x: 0,
    y: 0,
    width: 100,
    height: 100,
    radius: 0,
  },
  Ellipse: {
    type: 'ellipse',
    x: 50,
    y: 50,
    width: 50,
    height: 50,
  },
  Polygon: {
    type: 'polygon',
    x: 0,
    y: 0,
    points: '0,1,0.95,0.31,0.59,-0.81,-0.59,-0.81,-0.95,0.31',
    scale: 50,
  },
};

export const CORE_SHAPE = {
  line: {
    width: 1,
    color: '#000000',
    alpha: 1,
  },
  fill: { color: '#ffffff', alpha: 1 },
};

export const EFFECT_TEMPLATES = {
  'Tint Red when HP is bellow 10%': {
    hint: 'Tint token red when HP falls bellow 10%',
    config: {
      'hp<=10%': {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {
          texture: {
            tint: '#ff0000',
          },
        },
        overlay: false,
        alwaysOn: false,
        disabled: false,
        overlayConfig: {
          effect: 'hp<=10%',
        },
        targetActors: null,
        group: 'Default',
      },
    },
  },
  'Health State Text Overlay': {
    hint: 'Displays text overlay based on percentage health.',
    config: {
      'hp>0 && hp<=25%': {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {},
        overlay: true,
        alwaysOn: false,
        disabled: false,
        overlayConfig: {
          parent: '',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: false,
          linkScale: false,
          linkDimensions: false,
          linkOpacity: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0,
          offsetY: 0.51,
          scaleX: 0.76,
          scaleY: 0.76,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 1,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: 'Critical',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#ff0000',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: null,
            },
          },
          effect: 'hp>0 && hp<=25%',
        },
        targetActors: null,
        group: 'Health State Overlay',
      },
      'hp>25% && hp<=50%': {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {},
        overlay: true,
        alwaysOn: false,
        disabled: false,
        overlayConfig: {
          parent: '',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: false,
          linkScale: false,
          linkDimensions: false,
          linkOpacity: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0,
          offsetY: 0.51,
          scaleX: 0.76,
          scaleY: 0.76,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 1,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: 'Bloodied',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#ff5900',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: null,
            },
          },
          effect: 'hp>25% && hp<=50%',
        },
        targetActors: null,
        group: 'Health State Overlay',
      },
      'hp>50% && hp<=75%': {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {},
        overlay: true,
        alwaysOn: false,
        disabled: false,
        overlayConfig: {
          parent: '',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: false,
          linkScale: false,
          linkDimensions: false,
          linkOpacity: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0,
          offsetY: 0.51,
          scaleX: 0.76,
          scaleY: 0.76,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 1,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: 'Wounded',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#ffbb00',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: null,
            },
          },
          effect: 'hp>50% && hp<=75%',
        },
        targetActors: null,
        group: 'Health State Overlay',
      },
      'hp>75%': {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {},
        overlay: true,
        alwaysOn: false,
        disabled: false,
        overlayConfig: {
          parent: '',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: false,
          linkScale: false,
          linkDimensions: false,
          linkOpacity: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0,
          offsetY: 0.51,
          scaleX: 0.76,
          scaleY: 0.76,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 1,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: 'Healthy',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#2bff00',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: null,
            },
          },
          effect: 'hp>75%',
        },
        targetActors: null,
        group: 'Health State Overlay',
      },
    },
  },
  'Health State Text Overlay - Passed Check': {
    hint: 'Same as `Health State Text Overlay` except also requiring the Token actor to have `Reveal Health` active effect applied to it.',
    config: {
      'Reveal Health && hp>0 && hp<=25%': {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {},
        overlay: true,
        alwaysOn: false,
        disabled: false,
        overlayConfig: {
          parent: '',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: false,
          linkScale: false,
          linkDimensions: false,
          linkOpacity: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0,
          offsetY: 0.51,
          scaleX: 0.76,
          scaleY: 0.76,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 1,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: 'Critical',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#ff0000',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: null,
            },
          },
          effect: 'Reveal Health && hp>0 && hp<=25%',
        },
        targetActors: null,
        group: 'Health State Overlay - Passed Check',
      },
      'Reveal Health && hp>25% && hp<=50%': {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {},
        overlay: true,
        alwaysOn: false,
        disabled: false,
        overlayConfig: {
          parent: '',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: false,
          linkScale: false,
          linkDimensions: false,
          linkOpacity: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0,
          offsetY: 0.51,
          scaleX: 0.76,
          scaleY: 0.76,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 1,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: 'Bloodied',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#ff5900',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: null,
            },
          },
          effect: 'Reveal Health && hp>25% && hp<=50%',
        },
        targetActors: null,
        group: 'Health State Overlay - Passed Check',
      },
      'Reveal Health && hp>50% && hp<=75%': {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {},
        overlay: true,
        alwaysOn: false,
        disabled: false,
        overlayConfig: {
          parent: '',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: false,
          linkScale: false,
          linkDimensions: false,
          linkOpacity: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0,
          offsetY: 0.51,
          scaleX: 0.76,
          scaleY: 0.76,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 1,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: 'Wounded',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#ffbb00',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: null,
            },
          },
          effect: 'Reveal Health && hp>50% && hp<=75%',
        },
        targetActors: null,
        group: 'Health State Overlay - Passed Check',
      },
      'Reveal Health && hp>75%': {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {},
        overlay: true,
        alwaysOn: false,
        disabled: false,
        overlayConfig: {
          parent: '',
          underlay: false,
          bottom: false,
          top: false,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: false,
          linkScale: false,
          linkDimensions: false,
          linkOpacity: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0,
          offsetY: 0.51,
          scaleX: 0.76,
          scaleY: 0.76,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 1,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: 'Healthy',
            fontFamily: 'Signika',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#2bff00',
            dropShadow: 'true',
            strokeThickness: 1,
            stroke: '#111111',
            curve: {
              radius: 0,
              invert: null,
            },
          },
          effect: 'Reveal Health && hp>75%',
        },
        targetActors: null,
        group: 'Health State Overlay - Passed Check',
      },
    },
  },
  'Fancy Nameplate': {
    hint: 'Displays a curved red nameplate underneath the token.',
    config: {
      'Token Nameplate': {
        imgName: '',
        imgSrc: '',
        priority: 50,
        config: {},
        overlay: true,
        alwaysOn: true,
        disabled: false,
        overlayConfig: {
          parent: '',
          underlay: false,
          bottom: false,
          top: true,
          inheritTint: false,
          linkRotation: false,
          animation: {
            relative: false,
            rotate: false,
            duration: 5000,
            clockwise: true,
          },
          linkMirror: false,
          linkScale: false,
          linkDimensions: false,
          linkOpacity: false,
          loop: true,
          playOnce: false,
          img: '',
          alpha: 1,
          tint: '',
          offsetX: 0,
          offsetY: -0.51,
          scaleX: 0.68,
          scaleY: 0.68,
          angle: 0,
          anchor: {
            x: 0.5,
            y: 0,
          },
          filter: 'NONE',
          alwaysVisible: false,
          limitedUsers: [],
          limitOnHover: false,
          limitOnControl: false,
          limitOnEffect: '',
          limitOnProperty: '',
          text: {
            text: '{{name}}',
            fontFamily: 'Modesto Condensed',
            fontSize: 36,
            letterSpacing: 0,
            fill: '#ff0000',
            dropShadow: 'true',
            strokeThickness: 3,
            stroke: '#111111',
            curve: {
              radius: 450,
              invert: true,
            },
          },
          shapes: [
            {
              line: {
                width: 1,
                color: '#111111',
                alpha: 1,
              },
              fill: {
                color: '#111111',
                alpha: 1,
              },
            },
          ],
          effect: 'Token Nameplate',
        },
        targetActors: null,
        group: 'Nameplate',
      },
    },
    'Info Box #1': {
      hint: 'Displays information about the token/actor when hovering over or controlling them. This box will adjust to canvas zoom.',
      config: {
        'Text Box Background': {
          imgName: '',
          imgSrc: '',
          priority: 50,
          config: {},
          overlay: true,
          alwaysOn: true,
          disabled: false,
          overlayConfig: {
            parent: '',
            underlay: false,
            bottom: false,
            top: true,
            inheritTint: false,
            linkRotation: false,
            animation: {
              relative: false,
              rotate: false,
              duration: 5000,
              clockwise: true,
            },
            linkMirror: false,
            linkScale: false,
            linkDimensions: false,
            linkOpacity: false,
            linkStageScale: true,
            loop: true,
            playOnce: false,
            img: '',
            alpha: 1,
            tint: '',
            offsetX: -0.55,
            offsetY: 0,
            scaleX: 0.73,
            scaleY: 0.73,
            angle: 0,
            anchor: {
              x: 0,
              y: 0.5,
            },
            filter: 'DropShadowFilter',
            filterOptions: {
              rotation: 45,
              distance: 16.9,
              color: '#000000',
              alpha: 0.52,
              shadowOnly: false,
              blur: 2,
              quality: 3,
            },
            alwaysVisible: false,
            limitedUsers: [],
            limitOnHover: true,
            limitOnControl: true,
            limitOnEffect: '',
            limitOnProperty: '',
            text: {
              text: '',
              fontFamily: 'Signika',
              fontSize: 36,
              letterSpacing: 0,
              fill: '#FFFFFF',
              dropShadow: 'true',
              strokeThickness: 1,
              stroke: '#111111',
              curve: {
                radius: 0,
                invert: false,
              },
            },
            shapes: [
              {
                shape: {
                  type: 'rectangle',
                  x: 0,
                  y: 0,
                  width: 450,
                  height: 200,
                  radius: 0,
                },
                line: {
                  width: 2,
                  color: '#ffffff',
                  alpha: 1,
                },
                fill: {
                  color: '#508fe2',
                  alpha: 0.55,
                },
              },
            ],
            effect: 'Text Box Background',
          },
          targetActors: null,
          group: 'Info Box',
        },
        'Actor AC': {
          imgName: '',
          imgSrc: '',
          priority: 50,
          config: {},
          overlay: true,
          alwaysOn: true,
          disabled: false,
          overlayConfig: {
            parent: 'Text Box Background',
            underlay: false,
            bottom: false,
            top: true,
            inheritTint: false,
            linkRotation: false,
            animation: {
              relative: false,
              rotate: false,
              duration: 5000,
              clockwise: true,
            },
            linkMirror: false,
            linkScale: false,
            linkOpacity: false,
            loop: true,
            playOnce: false,
            img: '',
            alpha: 1,
            tint: '',
            offsetX: -0.25,
            offsetY: 0.46,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            anchor: {
              x: 0,
              y: 0,
            },
            filter: 'NONE',
            alwaysVisible: false,
            limitedUsers: [],
            limitOnHover: false,
            limitOnControl: false,
            text: {
              text: 'AC: {{actor.system.attributes.ac.value}}',
              fontFamily: 'Signika',
              fontSize: 36,
              letterSpacing: 0,
              fill: '#FFFFFF',
              dropShadow: 'true',
              strokeThickness: 1,
              stroke: '#111111',
              curve: {
                radius: 0,
                invert: null,
              },
            },
            effect: 'Actor AC',
          },
          targetActors: null,
          group: 'Info Box',
        },
        'actor¶system¶resources¶legact¶max>0': {
          imgName: '',
          imgSrc: '',
          priority: 50,
          config: {},
          overlay: true,
          alwaysOn: false,
          disabled: false,
          overlayConfig: {
            parent: 'Text Box Background',
            underlay: false,
            bottom: false,
            top: true,
            inheritTint: false,
            linkRotation: false,
            animation: {
              relative: false,
              rotate: false,
              duration: 5000,
              clockwise: true,
            },
            linkMirror: false,
            linkScale: false,
            linkOpacity: false,
            loop: true,
            playOnce: false,
            img: '',
            alpha: 1,
            tint: '',
            offsetX: 0.47,
            offsetY: -0.02,
            scaleX: 0.5,
            scaleY: 0.5,
            angle: 0,
            anchor: {
              x: 0,
              y: 0,
            },
            filter: 'NONE',
            alwaysVisible: false,
            limitedUsers: [],
            limitOnHover: false,
            limitOnControl: false,
            text: {
              text: 'Legendary: Action {{actor.system.resources.legact.value}}/{{actor.system.resources.legact.max}} Resistance {{actor.system.resources.legres.value}}/{{actor.system.resources.legres.max}}',
              fontFamily: 'Signika',
              fontSize: 36,
              letterSpacing: 0,
              fill: '#FFFFFF',
              dropShadow: 'true',
              strokeThickness: 1,
              stroke: '#111111',
              curve: {
                radius: 0,
                invert: null,
              },
            },
            effect: 'actor¶system¶resources¶legact¶max>0',
          },
          targetActors: null,
          group: 'Info Box',
        },
        'hp<=40%': {
          imgName: '',
          imgSrc: '',
          priority: 50,
          config: {},
          overlay: true,
          alwaysOn: false,
          disabled: false,
          overlayConfig: {
            parent: 'Text Box Background',
            underlay: false,
            bottom: false,
            top: true,
            inheritTint: false,
            linkRotation: false,
            animation: {
              relative: false,
              rotate: false,
              duration: 5000,
              clockwise: true,
            },
            linkMirror: false,
            linkScale: false,
            linkOpacity: false,
            loop: true,
            playOnce: false,
            img: '',
            alpha: 1,
            tint: '',
            offsetX: 0.47,
            offsetY: 0.23,
            scaleX: 0.82,
            scaleY: 0.82,
            angle: 0,
            anchor: {
              x: 0,
              y: 0,
            },
            filter: 'NONE',
            alwaysVisible: false,
            limitedUsers: [],
            limitOnHover: false,
            limitOnControl: false,
            text: {
              text: 'HP: {{actor.system.attributes.hp.value}}/{{actor.system.attributes.hp.max}}',
              fontFamily: 'Signika',
              fontSize: 36,
              letterSpacing: 0,
              fill: '#ff0000',
              dropShadow: 'true',
              strokeThickness: 1,
              stroke: '#6b6b6b',
              curve: {
                radius: 0,
                invert: null,
              },
            },
            effect: 'hp<=40%',
          },
          targetActors: null,
          group: 'Info Box',
        },
        'hp>40%': {
          imgName: '',
          imgSrc: '',
          priority: 50,
          config: {},
          overlay: true,
          alwaysOn: false,
          disabled: false,
          overlayConfig: {
            parent: 'Text Box Background',
            underlay: false,
            bottom: false,
            top: true,
            inheritTint: false,
            linkRotation: false,
            animation: {
              relative: false,
              rotate: false,
              duration: 5000,
              clockwise: true,
            },
            linkMirror: false,
            linkScale: false,
            linkOpacity: false,
            loop: true,
            playOnce: false,
            img: '',
            alpha: 1,
            tint: '',
            offsetX: 0.47,
            offsetY: 0.23,
            scaleX: 0.82,
            scaleY: 0.82,
            angle: 0,
            anchor: {
              x: 0,
              y: 0,
            },
            filter: 'NONE',
            alwaysVisible: false,
            limitedUsers: [],
            limitOnHover: false,
            limitOnControl: false,
            text: {
              text: 'HP: {{actor.system.attributes.hp.value}}/{{actor.system.attributes.hp.max}}',
              fontFamily: 'Signika',
              fontSize: 36,
              letterSpacing: 0,
              fill: '#FFFFFF',
              dropShadow: 'true',
              strokeThickness: 1,
              stroke: '#6b6b6b',
              curve: {
                radius: 0,
                invert: null,
              },
            },
            effect: 'hp>40%',
          },
          targetActors: null,
          group: 'Info Box',
        },
        Mods: {
          imgName: '',
          imgSrc: '',
          priority: 50,
          config: {},
          overlay: true,
          alwaysOn: true,
          disabled: false,
          overlayConfig: {
            parent: 'Text Box Background',
            underlay: false,
            bottom: false,
            top: true,
            inheritTint: false,
            linkRotation: false,
            animation: {
              relative: false,
              rotate: false,
              duration: 5000,
              clockwise: true,
            },
            linkMirror: false,
            linkScale: false,
            linkOpacity: false,
            loop: true,
            playOnce: false,
            img: '',
            alpha: 1,
            tint: '',
            offsetX: 0,
            offsetY: -0.38,
            scaleX: 0.57,
            scaleY: 0.57,
            angle: 0,
            anchor: {
              x: 0.5,
              y: 0.5,
            },
            filter: 'NONE',
            alwaysVisible: false,
            limitedUsers: [],
            limitOnHover: false,
            limitOnControl: false,
            text: {
              text: 'STR {{actor.system.abilities.str.mod}}  DEX {{actor.system.abilities.dex.mod}}  CON {{actor.system.abilities.con.mod}}  INT {{actor.system.abilities.int.mod}}  WIS {{actor.system.abilities.wis.mod}}  CHA {{actor.system.abilities.cha.mod}}',
              fontFamily: 'Signika',
              fontSize: 36,
              letterSpacing: 0,
              fill: '#FFFFFF',
              dropShadow: 'true',
              strokeThickness: 1,
              stroke: '#111111',
              curve: {
                radius: 0,
                invert: null,
              },
            },
            effect: 'Mods',
          },
          targetActors: null,
          group: 'Info Box',
        },
        'Movement Fly': {
          imgName: '',
          imgSrc: '',
          priority: 50,
          config: {},
          overlay: true,
          alwaysOn: true,
          disabled: false,
          overlayConfig: {
            parent: 'Text Box Background',
            underlay: false,
            bottom: false,
            top: true,
            inheritTint: false,
            linkRotation: false,
            animation: {
              relative: false,
              rotate: false,
              duration: 5000,
              clockwise: true,
            },
            linkMirror: false,
            linkScale: false,
            linkOpacity: false,
            loop: true,
            playOnce: false,
            img: '',
            alpha: 1,
            tint: '',
            offsetX: -0.36,
            offsetY: -0.16,
            scaleX: 0.33,
            scaleY: 0.33,
            angle: 0,
            anchor: {
              x: 0.5,
              y: 0.5,
            },
            filter: 'NONE',
            alwaysVisible: false,
            limitedUsers: [],
            limitOnHover: false,
            limitOnControl: false,
            text: {
              text: 'Fly {{actor.system.attributes.movement.fly}}, Swim {{actor.system.attributes.movement.swim}}',
              fontFamily: 'Signika',
              fontSize: 36,
              letterSpacing: 0,
              fill: '#FFFFFF',
              dropShadow: 'true',
              strokeThickness: 1,
              stroke: '#111111',
              curve: {
                radius: 0,
                invert: null,
              },
            },
            effect: 'Movement Fly',
          },
          targetActors: null,
          group: 'Info Box',
        },
        'Movement Label': {
          imgName: '',
          imgSrc: '',
          priority: 50,
          config: {},
          overlay: true,
          alwaysOn: true,
          disabled: false,
          overlayConfig: {
            parent: 'Text Box Background',
            underlay: false,
            bottom: false,
            top: true,
            inheritTint: false,
            linkRotation: false,
            animation: {
              relative: false,
              rotate: false,
              duration: 5000,
              clockwise: true,
            },
            linkMirror: false,
            linkScale: false,
            linkOpacity: false,
            loop: true,
            playOnce: false,
            img: '',
            alpha: 1,
            tint: '',
            offsetX: -0.25,
            offsetY: 0.2,
            scaleX: 0.61,
            scaleY: 0.61,
            angle: 0,
            anchor: {
              x: 0,
              y: 0,
            },
            filter: 'NONE',
            alwaysVisible: false,
            limitedUsers: [],
            limitOnHover: false,
            limitOnControl: false,
            text: {
              text: 'Movement',
              fontFamily: 'Signika',
              fontSize: 36,
              letterSpacing: 0,
              fill: '#FFFFFF',
              dropShadow: 'true',
              strokeThickness: 1,
              stroke: '#111111',
              curve: {
                radius: 0,
                invert: null,
              },
            },
            effect: 'Movement Label',
          },
          targetActors: null,
          group: 'Info Box',
        },
        'Movement Walk': {
          imgName: '',
          imgSrc: '',
          priority: 50,
          config: {},
          overlay: true,
          alwaysOn: true,
          disabled: false,
          overlayConfig: {
            parent: 'Text Box Background',
            underlay: false,
            bottom: false,
            top: true,
            inheritTint: false,
            linkRotation: false,
            animation: {
              relative: false,
              rotate: false,
              duration: 5000,
              clockwise: true,
            },
            linkMirror: false,
            linkScale: false,
            linkOpacity: false,
            loop: true,
            playOnce: false,
            img: '',
            alpha: 1,
            tint: '',
            offsetX: -0.36,
            offsetY: -0.03,
            scaleX: 1,
            scaleY: 1,
            angle: 0,
            anchor: {
              x: 0.5,
              y: 0.5,
            },
            filter: 'NONE',
            alwaysVisible: false,
            limitedUsers: [],
            limitOnHover: false,
            limitOnControl: false,
            text: {
              text: '{{actor.system.attributes.movement.walk}}ft',
              fontFamily: 'Signika',
              fontSize: 36,
              letterSpacing: 0,
              fill: '#FFFFFF',
              dropShadow: 'true',
              strokeThickness: 1,
              stroke: '#111111',
              curve: {
                radius: 0,
                invert: null,
              },
            },
            effect: 'Movement Walk',
          },
          targetActors: null,
          group: 'Info Box',
        },
        'Token Name': {
          imgName: '',
          imgSrc: '',
          priority: 50,
          config: {},
          overlay: true,
          alwaysOn: true,
          disabled: false,
          overlayConfig: {
            parent: 'Text Box Background',
            underlay: false,
            bottom: false,
            top: true,
            inheritTint: false,
            linkRotation: false,
            animation: {
              relative: false,
              rotate: false,
              duration: 5000,
              clockwise: true,
            },
            linkMirror: false,
            linkScale: false,
            linkOpacity: false,
            loop: true,
            playOnce: false,
            img: '',
            alpha: 1,
            tint: '',
            offsetX: 0.47,
            offsetY: 0.35,
            scaleX: 0.77,
            scaleY: 0.77,
            angle: 0,
            anchor: {
              x: 0,
              y: 0.5,
            },
            filter: 'NONE',
            alwaysVisible: false,
            limitedUsers: [],
            limitOnHover: false,
            limitOnControl: false,
            text: {
              text: 'Name: {{name}}',
              fontFamily: 'Signika',
              fontSize: 36,
              letterSpacing: 0,
              fill: '#FFFFFF',
              dropShadow: 'true',
              strokeThickness: 1,
              stroke: '#111111',
              curve: {
                radius: 0,
                invert: null,
              },
            },
            effect: 'Token Name',
          },
          targetActors: null,
          group: 'Info Box',
        },
      },
    },
  },
};
